
const ArticoliSelfImprovment = [
       {
              id: 15,
        titolo : "Confidence Is a Skill: How to Build It Daily",
          sottotitolo:"Practical exercises to boost self-esteem and show up powerfully in life.",
         contenuto: ["Let’s get one thing straight: confidence isn’t something you’re born with.",
        "It’s not reserved for the loudest person in the room or the one who always knows what to say.",
        "Confidence is a skill. And like any skill, it can be learned, practiced, and strengthened day by day.",
        " So if you’ve ever thought, “I wish I were more confident,” guess what? ",
        "You’re already halfway there. You want it. Now let’s build it.",
        "💭 Reframing Confidence",
        "Confidence isn’t about being fearless. It’s about being brave with your fear.",
        "It’s showing up even when your voice shakes. It’s trusting yourself enough to try, fail, and try again.",
        "And the best part? You don’t need a big moment to build it.",
        "You can start with tiny, daily choices that add up to a stronger, bolder you. ",
        "🔑 6 Daily Habits to Build Confidence ",
        "1. Keep Promises to Yourself",
         "Confidence grows when you trust yourself. Start small: “I’ll go for a walk today.” “I’ll drink more water.”",
         "Every time you follow through, you prove to yourself that you’re reliable and that builds self-respect.",
         "2. Speak Kindly to Yourself",
         " Your inner voice matters. Replace “I’m so awkward” with “I’m learning.”",
          "3. Do One Thing That Scares You (Just a Little)",
          " Send the email. Ask the question. Wear the bold lipstick.",
          "Confidence isn’t built in your comfort zone it’s built just outside of it.",
           "Stretch gently, and celebrate every brave step.",
            "and saying no will feel less like confrontation and more like self-respect.",
            "4. Practice Good Posture",
            "Sounds basic, but it works. Shoulders back, chin up, deep breath.",
            "Your body language affects your mindset. Walk like you belong - because you do.",
        "5. Celebrate Small Wins",
    "Finished a task? Spoke up in a meeting? Didn’t spiral after a mistake? That’s a win.",
 "Confidence grows when you acknowledge your progress, not just perfection.",
  "6. Surround Yourself with Uplifting Energy",
   "Your environment matters. Spend time with people who cheer you on, not tear you down.",
    "Curate your social media, your playlists, your spaces",
     "make them reflect the version of you you’re becoming.",
    "SO...",
    "Confidence isn’t a switch you flip — it’s a muscle you build.",
    "And every time you show up, even imperfectly, you’re strengthening it.",
    "So be gentle. Be bold. Be consistent.",
    "You’re not waiting to become confident",
    "you’re becoming confident. ",
    "One day, one choice, one brave moment at a time."
],
        immagine:"/confidence.jpg"
    },
       {
              id: 16,
        titolo : "Goal Setting That Actually Works: Ditch the Hustle Culture",
          sottotitolo:"A softer, more sustainable approach to achieving personal goals.",
         contenuto: ["Let’s be honest—goal setting has been hijacked by hustle culture.",
        " Somewhere along the way, it stopped being about growth and started feeling like a never-ending to-do list.",
        "More. Faster. Bigger. Better.",
        "And if you’re not constantly grinding? You’re “falling behind.”",
        "But here’s the truth: you’re not behind. You’re human.",
        " And goal setting doesn’t have to feel like pressure. It can feel like peace. Like purpose.",
        "Why Hustle Culture Doesn’t Work (At Least Not for Your Soul) ",
        "Hustle culture glorifies burnout. It tells you that rest is lazy,",
        " that productivity equals worth, and that success only counts if it’s loud and fast.",
        "But here’s what it doesn’t tell you:",
        "- You can be ambitious and gentle.",
           "- You can grow without grinding.",
              "- You can set goals that feel nourishing not exhausting.",
        "A New Way to Set Goals (That Actually Stick) ",
        "Let’s flip the script. Here’s how to set goals that feel aligned, sustainable, and soul-sparking.",
         "1. Start with How You Want to Feel",
         "Instead of asking “What do I want to achieve?”, ask:",
         " “How do I want to feel this month?”",
         "Peaceful? Energized? Creative? Grounded?",
          "Let your goals support those feelings.",
          "Example: If you want to feel peaceful, your goal might be “Create a calming night routine”",
          " instead of “Wake up at 5AM every day.”",
          " 2. Set Soul Goals, Not Just Smart Goals",
           "SMART goals are great for structure. But soul goals ask:",
            "“Does this light me up?”",
            " “Is this aligned with who I’m becoming?”",
            " 3. Break It Down (Tiny Steps = Big Wins)",
            "Big goals are beautiful but they need bite-sized steps.",
        "Instead of “Write a book,” try:",
     "- “Write for 20 minutes every morning.”",
      "- “Outline one chapter this week.”",
       "Small steps build momentum. And momentum builds confidence.",
        "4. Track Progress with Compassion",
         "Check in weekly - not to judge, but to reflect.",
          "Ask:",
         "- What worked?",
         "- What felt good?",
          "- What needs adjusting?",
           "No guilt. Just gentle awareness.",
            "5. Celebrate Without Conditions",
             "You don’t have to “earn” celebration.",
            "Celebrate showing up. Celebrate trying. Celebrate resting.",
        "Because every step toward your goal no matter how small is worth honoring.",
    "💬 Final Thoughts",
"Take a breath. Get quiet. Ask yourself what you really want.",
"Then build it—slowly, intentionally, and with love.",],
        immagine:"/goals.jpg"
    }
]
export default ArticoliSelfImprovment;