
const ArticoliLifeStyle = [
       {
              id: 9,
        titolo : "Budgeting with Style: Financial Wellness Without Sacrificing Fun",
          sottotitolo:"Smart money tips for living well and saving wisely.",
        contenuto: ["Let’s be real—budgeting has a bad reputation. It sounds like spreadsheets, guilt, and saying no to brunch.",
        " But here’s the truth: budgeting isn’t about punishment. It’s about freedom. ",
        "It’s about designing a life where your money supports your joy, not steals it.",
        " And yes, you can still have your oat milk latte.",
        "Reframing the Budget Mindset",
        "Budgeting isn’t about cutting out everything you love. It’s about choosing what matters most and making space for it. ",
        "Instead of thinking: ",
        "“I can’t afford this.” ",
        "Try:",
        " “I’m choosing to spend on what lights me up.” ",
        "That shift alone makes budgeting feel less like a cage ",
        "and more like a closet full of outfits you actually want to wear.",
        "Step 1: Know Your Numbers (Without Panic)",
         "Start simple: What’s coming in? (Your income) What’s going out? (Rent, bills, subscriptions, etc.)",
         " What’s left? (Your flexible spending)",
         "You don’t need to be a finance expert. Just get familiar.",
         " Think of it like checking the weather before choosing your outfit it helps you plan, not panic.",
          "Step 2: Create a “Joy Fund”",
          " Yes, seriously. Set aside money just for fun. Whether it’s €20 a week for coffee dates, books, or spontaneous gelato runs",
          " this fund is sacred. It keeps you from feeling deprived and helps you spend guilt-free.",
           "Step 3: Practice Conscious Spending",
            "Before buying something, ask: Do I really want this, or am I bored/stressed?",
            " Will I still love this next month? Is this aligned with the life I’m building?",
            " This isn’t about saying no—it’s about saying yes with intention.",
            " Step 4: Use Tools That Feel Cute (and Useful)",
           "Budgeting apps don’t have to be boring. Try ones with clean design, goal trackers,",
           " and reminders that feel like a bestie cheering you on.",
            " Some even let you name your savings goals (“Paris Trip 💕” or “Emergency Fund, But Make It Chic”).",
            " Step 5: Celebrate Small Wins",
            "Saved €50 this month? Amazing. Cooked at home three nights in a row? Iconic.",
          "Paid off a credit card? You’re a legend. Financial wellness is a journey celebrate every step.",
        "You don’t have to choose between financial wellness and fun. You can have both.",
      "So go ahead—build that budget. Make it pretty. Make it powerful. And make it yours."],
        immagine:"/budgeting.jpg"
    },
       {
              id: 10,
        titolo : "The Joy of Cooking for One: Easy Recipes That Feel Like Self-Care",
          sottotitolo:"Delicious, nourishing meals that celebrate solo living.",
        contenuto: ["Let’s be honest—cooking for one can feel… meh.",
        " Like, why go through all that effort when you could just order sushi and binge-watch your favorite show? ",
        "But here’s the thing: cooking for yourself isn’t just about food. It’s about care.",
        "It’s about creating something with your own hands and saying, “I’m worth the effort.” ",
        "Cooking for one can be joyful, grounding, and even a little romantic.",
        "You just need the right mindset—and a few go-to recipes that feel like a hug in a bowl. ",
        "Reframing Solo Cooking",
        "Cooking for yourself isn’t lonely. It’s intimate. It’s personal.  ",
        "It’s a moment to slow down, nourish your body, and connect with yourself.",
        " It’s lighting a candle while you stir pasta. It’s plating your meal like you’re on MasterChef.",
        "t’s dancing in the kitchen while your veggies roast.",
        "Solo cooking is self-care in action.",
         "🥗 5 Easy Recipes That Feel Like Love",
         " These recipes are simple, quick, and designed to make you feel good",
         "without leaving a mountain of dishes behind.",
         "1. Creamy Avocado Toast with a Twist",
          "Why it feels like self-care: It’s fresh, satisfying, and takes 5 minutes.",
          " Ingredients:",
          " - 1 slice of sourdough or whole grain bread",
          "- -½ ripe avocado",
          "- A squeeze of lemon",
          "Optional: feta, cherry tomatoes, or a drizzle of honey",
           "Tip: Mash the avocado with the lemon, then layer with toppings that make you smile.",
            "2. One-Pan Lemon Garlic Pasta",
            "Why it feels like self-care: Minimal cleanup, maximum flavor.",
            " Ingredients:",
            "- Spaghetti or linguine",
               "- Olive oil",
                  "- Garlic (lots of it)",
                     "- Lemon zest and juice",
                        "- Parmesan or nutritional yeast",
                          "- Fresh parsley",
            " Tip: Cook pasta, sauté garlic in olive oil, toss everything together with lemon and cheese.",
          "Add a glass of wine and call it a date.",
          "3. Cozy Chickpea Stew",
            "Why it feels like self-care: Warm, comforting, and packed with nutrients.",
            " Ingredients:",
            "- Canned chickpeas",
               "- Diced tomatoes",
                  "- Onion, garlic, and spinach",
                     "- Spices: cumin, paprika, salt",
                        "- Coconut milk or veggie broth",
            " Tip: Simmer everything in one pot. Serve with rice or crusty bread.",
          "Bonus: leftovers taste even better.", 
           "4. Savory Oats with Egg and Greens",
            "Why it feels like self-care: Unexpected, nourishing, and surprisingly delicious.",
            " Ingredients:",
            "- Rolled oats",
               "- Water or veggie broth",
                  "- Salt, pepper",
                     "- Sautéed spinach or kale",
                        "- Fried or poached egg",
            " Tip: Cook oats in broth, top with greens and egg. Add chili oil if you’re feeling spicy.",
             "5. Banana Mug Cake for Dessert",
            "Why it feels like self-care: Sweet, quick, and made just for you.",
            " Ingredients:",
            "- 1 ripe banana",
               "- 1 egg",
                  "- 2 tbsp oat flour or almond flour",
                     "- A pinch of cinnamon (obv)",
                        "- Optional: chocolate chips or peanut butter",
            " Tip: Mix in a mug, microwave for 90 seconds, and enjoy warm with a spoon and a smile.",
            " Cooking for one isn’t about being alone. It’s about being with yourself.",
            " It’s about choosing joy, flavor, and nourishment—even when no one’s watching.",
          "And yes, you can still order sushi sometimes. But tonight? Let’s cook."],
        immagine:"/cooking.jpg"
    },
       {
              id: 11,
        titolo : "Design a Life You Love: Vision Boards and Intentional Living",
          sottotitolo:"Use visual tools to have your dream lifestyle in front of you.",
        contenuto: ["Let’s be honest—life can feel like a whirlwind. Between work, relationships, social media,",
        "and trying to remember to drink enough water, it’s easy to get swept up in the chaos ",
        "and forget what's your actual goal.",
        " That’s where intentional living comes in. It’s not about having everything figured out. ",
        "It’s about choosing, every day, to move toward the life you actually want",
        "not the one you’re “supposed” to want.",
        "And one of the most powerful tools to help you do that? A vision board. ",
        "What Is Intentional Living, Really? ",
        "Intentional living means making choices that align with your values, dreams, and desires.",
        " it’s about asking yourself: “Does this support the life I’m trying to create?” ",
        "It’s not about perfection. It’s about presence. It’s about showing up for yourself with clarity and purpose",
        "even when things get messy.",
         "Why Vision Boards Work",
         "Vision boards are visual representations of your goals, dreams, and intentions..",
         " Think of them as a Pinterest board for your soul but in real life.",
         " They work because:",
          "-They clarify your desires.",
          "-They keep your goals front and center. Out of sight = out of mind.",
          " -They activate your subconscious. Seeing your dreams daily helps your brain believe they’re possible.",
           "-They’re fun. And joy is a powerful motivator.",
            "How to Create a Vision Board That Actually Inspires You?",
            " You don’t need fancy supplies or a Pinterest-perfect aesthetic. You just need intention.",
            " Step 1: Reflect",
            " Ask yourself:  What do I want more of in my life? What do I want to feel every day? What am I ready to release?",
          "Step 2: Gather",
        "Collect images, words, quotes, and colors that spark something in you.",
        " You can use: Magazines, Pinterest, Old photos, Affirmations",
      "Step 3: Assemble",
    "Arrange everything on a board, journal page, or even your wall. There’s no wrong way. Just make sure it feels you.",
  "Step 4: Place It Where You’ll See It",
"Your vision board should live somewhere visible, your bedroom, workspace, or even as your phone wallpaper.",
" Let it be a daily reminder of where you’re headed."],
        immagine:"/visionb.jpg"
    },
       {
              id: 7,
        titolo : "Friendship in Your 20s: Navigating Change and Deepening Connection",
          sottotitolo:"Advice on maintaining meaningful relationships as life evolves.",
        contenuto: ["Let’s be honest—friendship in your 20s is a wild ride. One minute you’re having sleepovers and sharing secrets over iced coffee,",
        " the next you’re texting “miss you” to someone you haven’t seen in six months. ",
        "It’s not that you stopped caring. It’s that life got real.",
        " Careers, relationships, moves, mental health… ",
        "your 20s are full of transitions. And friendships? They feel it too.",
        " But here’s the good news: change doesn’t mean loss. ",
        "It can mean growth, depth, and a new kind of closeness if you’re willing to show up. ",
        "Why Friendships Shift in Your 20s ?",
        "Different life paths: One friend is traveling the world, another is deep in grad school, ",
        "and you’re figuring out what “balance” even means.",
        "Less time, more responsibility: Adulting is real. Schedules clash. Energy runs low. ",
        "Personal growth: As you evolve, your values and boundaries do too",
        "and not every friendship grows at the same pace.",
         "It’s normal. It’s human. And it doesn’t mean you’re failing at friendship.",
         " How to Deepen Connection (Even When Life Gets Busy)",
         "1. Be Intentional, Not Perfect",
         " You don’t need to text every day. But a voice note, a meme,",
          "or a “thinking of you” message can go a long way. It’s not about frequency it’s about sincerity.",
          " 2. Create Rituals",
          "Monthly brunch. Weekly FaceTime. A shared playlist.",
          "3. Talk About the Hard Stuff",
           "Friendship isn’t just laughs and wine nights. It’s “I’m struggling.” It’s “I feel distant.”",
           " Vulnerability deepens trust.",
            "4. Celebrate Each Other’s Wins.",
            "Even if you’re in different seasons, cheer each other on. Your friend’s success isn’t your failure",
            "it’s proof that growth is possible.",
            " 5. Let Go of Guilt",
            " You’re allowed to change. You’re allowed to outgrow connections. ",
            "You’re allowed to miss someone and still move forward.",
          "Final toughts",
        "Friendship in your 20s isn’t about having a huge circle. It’s about having a few people who get you.",
      "Who grow with you. Who show up even when life is messy.",
    "So reach out. Be honest. Make space. And remember: the best friendships aren’t perfect they’re real."],
        immagine:"/friendship.jpg"
    }
]
export default ArticoliLifeStyle;