
const ArticoliSelfCare = [
    {
        id: 1,
        titolo : "The Morning Routine That Actually Feels Good",
        sottotitolo :"A gentle, realistic morning routine that sets the tone for a better day.",
        contenuto: ["Let’s be real: mornings can be rough. I used to hit snooze five times, scroll through Instagram",
        "before even brushing my teeth, and somehow still feel behind before 9AM. Sound familiar?",
        "But here’s the thing I didn’t need a 5AM miracle routine or a productivity bootcamp. I just needed",
        "a few gentle rituals that made me feel like I was showing up for myself. And girl, it changed everything. ",
        "✨ Step 1: Hydrate Before You Hustle",
        "Before you reach for your phone or your coffee, drink a glass of water. It’s basic, I know but it’s ",
        "like giving your body a little “good morning” hug. I keep mine on my nightstand so I don’t forget.",
        "☀️ Step 2: Let the Light In ",
        "Open your curtains. Step onto your balcony. Let the sun kiss your face. Natural light helps reset",
        " your internal clock and boosts your mood. Bonus points if you whisper “I’m a radiant queen” while doing it. ",
        "🧘‍♀️ Step 3: Move Your Body (Just a Little)",
        "You don’t need a full workout. Stretch. Dance to your favorite song. Do five squats while brushing",
         "your teeth. Movement wakes up your body and reminds you that you’re alive and powerful.",
         " 📓 Step 4: Journal for 5 Minutes",
         "Write down how you feel, what you’re grateful for, or what you want to focus on today. It doesn’t",
         "have to be deep—just honest. This tiny habit helped me stop spiraling and start grounding.",
          "🍓 Step 5: Eat Something That Loves You Back",
          "Whether it’s a smoothie, oatmeal, or just a banana with peanut butter, choose something that fuels you.",
          "Not just physically, but emotionally. Breakfast is self-respect in edible form.",
           "💬 Final Thoughts",
            "You don’t have to do all five. You don’t have to do them perfectly. But even one small act of care in the morning can shift your whole vibe.",
            " You’re not lazy. You’re learning. And that’s beautiful.",
            " So tomorrow morning, try one thing. Just one. And let it be a love letter to yourself."],
        immagine:"/goodmorning.jpg"
    },
     {
        id: 2,
        titolo : "Mental Decluttering: How to Quiet the Noise in Your Head",
        sottotitolo :"Tackling mental overload and creating space for clarity.",
        contenuto: ["Ever feel like your brain has 47 tabs open and none of them are loading? Same.",
        "Between work, social media, and that random thing you forgot to do last week, it’s no wonder we feel mentally cluttered.",
        "But here’s the truth: your mind deserves peace, not pressure.",
        "And decluttering it doesn’t require a retreat in Bali (though that sounds nice). It just takes a few intentional shifts.",
        "📝 Step 1: Do a Brain Dump",
        "Grab a notebook and write down everything swirling in your head—tasks, worries, random thoughts. ",
        "Don’t organize it. Just get it out. It’s like clearing your desktop so you can finally see the wallpaper.",
        "📵 Step 2: Take a Digital Detox (Even Just for an Hour) ",
        "Turn off notifications. Log out of Instagram. Put your phone in another room.",
        " You’ll be shocked at how quiet your mind becomes when your screen isn’t constantly buzzing. ",
        "🎯 Step 3: Choose One Thing",
        "Instead of juggling five priorities, pick one. Just one. Focus on it. Finish it. Celebrate it.",
         "You’ll feel more accomplished than trying to do everything halfway.",
         "And remember:",
         " Mental clarity isn’t about perfection it’s about presence.",
         "You’re allowed to pause. You’re allowed to breathe. And you’re allowed to take up space in your own mind.",
    ],
        immagine:"/declutter-mind.jpg"
    },
     {
        id: 3,
        titolo : "Digital Self-Care: Protecting Your Energy Online",
        sottotitolo :"Navigating social media and screen time with intention.",
        contenuto: ["Scrolling used to be my escape. Now? It’s often the thing I need escaping from.",
        "Between comparison traps, doomscrolling, and endless notifications, our digital lives can drain us fast.",
        "Digital self-care is real self-care. And it starts with intention.",
        "FIRST THING FIRST : Unfollow What Doesn’t Nourish You ",
        "That influencer who makes you feel “less than”? That account that’s always negative?",
        "You can unfollow. Curate your feed like you curate your closet only keep what fits and feels good. ",
        "YOU CAN ALSO: Set App Limits",
        "Most phones let you set daily time limits for apps. ",
        "Use them. It’s like giving your brain a bedtime.",
        "REMEMBER TO: Follow Inspiration, Not Comparison ",
        "Fill your feed with creators who uplift you, teach you, make you laugh.",
        "Social media should be a garden, not a battlefield.",
         "FINAL THOUGHT",
         " “It’s okay to disconnect. Your peace matters more than any notification.",
         "The online world can wait—your well-being can’t",
           ],
        immagine:"/digital-care.jpg"
    },
     {
        id: 4,
        titolo : "Romantic Life: Turning Everyday Tasks Into something beautiful",
        sottotitolo :"A gentle, realistic morning routine that sets the tone for a better day.",
        contenuto: ["Washing dishes with a candle lit and music playing? That’s my new love language.",
        "urns out, life doesn’t have to be glamorous to feel magical.",
        "Romanticizing the mundane is about finding joy in the everyday.",
        "It’s about turning “ugh” into “mmm.” ",
        "SO WHAT SHOULD YOU DO?",
        "🕯️ Step 1: Add Atmosphere",
        "Light a candle while you clean. Play your favorite playlist while folding laundry.",
        "Wear perfume just because. Mood matters. ",
        "🍵 Step 2: Make It a Ritual",
        "Instead of rushing through tasks, slow down. Make tea like it’s a ceremony. ",
        "Journal like you’re writing poetry. Even brushing your hair can be a moment of care.",
        "👗 Step 3: Dress Up for Yourself",
         "Put on earrings for your grocery run. Wear your favorite sweater while working from home.",
         " You don’t need a reason to feel cute.",
         "Ordinary moments can be extraordinary when you show up with intention.",
         " You don’t need a vacation to feel alive you just need to notice the beauty already around you.",
         ],
        immagine:"/romanticize.jpg"
    },
      
] 
export default ArticoliSelfCare;